const colors = ["green", "red", "Rgba(237, 231, 225)", "purple"]

const btn = document.getElementById('btnn')

// when selecting a class from html we need to include a . symbol
const chng_color = document.querySelector(".chng_color")

btn.addEventListener('click', function(){
    // we want to select a random number generated by the computer 
    // which is between 0-3 , so everytime we click the button we get a totally different value.
    const randomNumber = Math.floor(Math.random()*colors.length)
    console.log(randomNumber)
    document.body.style.backgroundColor = colors[randomNumber]
    chng_color.textContent = colors[randomNumber]
})

// in this small excercise , we created a button in the html file which when clicked changes the background color of the 
// page.

